app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/jdbcpractice
      username: postgres
      password: 'postgres'
      pool-size: 30




#
#  spring.datasource.url=jdbc:postgresql://localhost:5432/jdbcpractice
#  spring.datasource.username=postgres
#  spring.datasource.password=postgres
#
#  spring.datasource.initialization-mode=always
#  spring.datasource.initialize=true
#  spring.datasource.schema=classpath:jdbc/schema.sql
#  spring.datasource.continue-on-error=true